insert into customer (id, first_name, last_name, email, mobile, job) values (1, 'Debora', 'Muldownie', 'dmuldownie0@studiopress.com', '0959964889', 'Technical Writer');
insert into customer (id, first_name, last_name, email, mobile, job) values (2, 'Ilka', 'Tomlin', 'itomlin1@delicious.com', '0879979999', 'Developer I');
insert into customer (id, first_name, last_name, email, mobile, job) values (3, 'Daniele', 'Gibbon', 'dgibbon2@mail.ru', '0969899799', 'VP Quality Control');
insert into customer (id, first_name, last_name, email, mobile, job) values (4, 'Hally', 'Rubinchik', 'hrubinchik3@hc360.com', '0799696998', 'Chemical Engineer');
insert into customer (id, first_name, last_name, email, mobile, job) values (5, 'Georgiana', 'Hennemann', 'ghennemann4@fastcompany.com', '0998988889', 'Actuary');
insert into customer (id, first_name, last_name, email, mobile, job) values (6, 'Felizio', 'Fouldes', 'ffouldes5@mozilla.org', '0599999989', 'Payment Adjustment Coordinator');
insert into customer (id, first_name, last_name, email, mobile, job) values (7, 'Clement', 'Minto', 'cminto6@gnu.org', '0698986964', 'Senior Quality Engineer');
insert into customer (id, first_name, last_name, email, mobile, job) values (8, 'Wenona', 'Agate', 'wagate7@e-recht24.de', '0787989989', 'Mechanical Systems Engineer');
insert into customer (id, first_name, last_name, email, mobile, job) values (9, 'Marcela', 'Muzzollo', 'mmuzzollo8@godaddy.com', '0968897989', 'Physical Therapy Assistant');
insert into customer (id, first_name, last_name, email, mobile, job) values (10, 'Jethro', 'Asman', 'jasman9@shop-pro.jp', '0999797899', 'Dental Hygienist');
